--- Makefile.orig	2015-03-19 20:45:55.000000000 +0100
+++ Makefile.patched	2015-03-19 20:58:48.000000000 +0100
@@ -143,7 +143,8 @@
 	to_string.cpp \
 	units.cpp \
 	utf8_string.cpp \
-	util.cpp
+	util.cpp \
+	emscripten_wrapper.cpp
 
 CSOURCES = cencode.c
 
@@ -187,6 +188,33 @@
 static: lib/libsass.a
 shared: $(LIBRARIES)
 
+js: static
+	emcc lib/libsass.a -o lib/libsass.js \
+ 		-O3 \
+		-s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" \
+		-s DISABLE_EXCEPTION_CATCHING=0 \
+		-s ALLOW_MEMORY_GROWTH=1 \
+		-s EMTERPRETIFY=1 \
+		-s EMTERPRETIFY_ASYNC=1 \
+		-s EMTERPRETIFY_WHITELIST=@../empterpreter_whitelist.json \
+		--memory-init-file 1
+
+js-debug: static
+	emcc lib/libsass.a -o lib/libsass.js \
+		-O0 \
+		-s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" \
+		-s DISABLE_EXCEPTION_CATCHING=0 \
+		-s ALLOW_MEMORY_GROWTH=1 \
+		-s EMTERPRETIFY=1 \
+		-s EMTERPRETIFY_ASYNC=1 \
+		-s EMTERPRETIFY_WHITELIST=@../empterpreter_whitelist.json \
+		-s ASSERTIONS=1 \
+		-s SAFE_HEAP=1 \
+		-s DEMANGLE_SUPPORT=1 \
+		--profiling-funcs \
+		--minify 0 \
+		--memory-init-file 1
+
 lib:
 	$(MKDIR) lib
 
@@ -235,7 +256,7 @@
 	$(RUBY_BIN) $(SASS_SPEC_PATH)/sass-spec.rb -c $(SASSC_BIN) $(LOG_FLAGS) $(SASS_SPEC_PATH)/spec/issues
 
 clean:
-	$(RM) $(RCOBJECTS) $(COBJECTS) $(OBJECTS) $(LIBRARIES) lib/*.a lib/*.so lib/*.dll lib/*.la
+	$(RM) $(RCOBJECTS) $(COBJECTS) $(OBJECTS) $(LIBRARIES) lib/*.a lib/*.so lib/*.dll lib/*.la lib/*.js lib/*.js.mem
 
 
 .PHONY: all debug debug-static debug-shared static shared install install-static install-shared sassc clean
