--- Makefile.orig	2015-09-09 14:30:05.000000000 +0300
+++ Makefile	2015-09-09 14:36:59.000000000 +0300
@@ -208,6 +208,35 @@
 debug-shared: CXXFLAGS := -g -DDEBUG -DDEBUG_LVL="$(DEBUG_LVL)" $(filter-out -O2,$(CXXFLAGS))
 debug-shared: shared

+js: static
+	emcc lib/libsass.a -o lib/libsass.js \
+ 		-O3 \
+		-s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" \
+		-s EXTRA_EXPORTED_RUNTIME_METHODS=@../exported_runtime_methods.json \
+		-s DISABLE_EXCEPTION_CATCHING=0 \
+		-s ALLOW_MEMORY_GROWTH=1 \
+		-s EMTERPRETIFY=1 \
+		-s EMTERPRETIFY_ASYNC=1 \
+		-s EMTERPRETIFY_WHITELIST=@../emterpreter_whitelist.json \
+		--memory-init-file 0
+
+js-debug: static
+	emcc lib/libsass.a -o lib/libsass.js \
+		-O0 \
+		-s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" \
+		-s EXTRA_EXPORTED_RUNTIME_METHODS=@../exported_runtime_methods.json \
+		-s DISABLE_EXCEPTION_CATCHING=0 \
+		-s ALLOW_MEMORY_GROWTH=1 \
+		-s EMTERPRETIFY=1 \
+		-s EMTERPRETIFY_ASYNC=1 \
+		-s EMTERPRETIFY_WHITELIST=@../emterpreter_whitelist.json \
+		-s ASSERTIONS=1 \
+		-s SAFE_HEAP=1 \
+		-s DEMANGLE_SUPPORT=1 \
+		--profiling-funcs \
+		--minify 0 \
+		--memory-init-file 0
+
 lib:
 	$(MKDIR) lib

@@ -299,7 +326,7 @@
 	$(RUBY_BIN) $(SASS_SPEC_PATH)/sass-spec.rb -c $(SASSC_BIN) $(LOG_FLAGS) $(SASS_SPEC_PATH)/spec/issues

 clean-objects: lib
-	-$(RM) lib/*.a lib/*.so lib/*.dll lib/*.la
+	-$(RM) lib/*.a lib/*.so lib/*.dll lib/*.la lib/*.js
 	-$(RMDIR) lib
 clean: clean-objects
 	$(RM) $(CLEANUPS)
